id: PC05A4040
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG5343
  instance_id: http://purl.bdrc.io/resource/IE1KG5343
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བོད་ཀྱི་རྩོམ་རིག་བྱུང་འཕེལ་གྱི་ལོ་རྒྱུས་དང་ཁྱད་ཆོས་རིག་འཛིན་བྱེ་བའི་རོལ་མཚོ།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - zang zu wen xue shi
  author: http://purl.bdrc.io/resource/P6531
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    419362c27f35405fa468048aec96d9f0:
      title: པོད ༡་བོད་ཀྱི་རྩོམ་རིག་བྱུང་འཕེལ་གྱི་ལོ་རྒྱུས་དང་ཁྱད་ཆོས་རིག་འཛིན་བྱེ་བའི་རོལ་མཚོ
      volume_number: 1
      base_file: UT1KG5343_I1KG5407_0000.txt
      reference: http://purl.bdrc.io/resource/VL9611256DB35809C1
      image_group: I1KG5407
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG5343
  - http://purl.bdrc.io/resource/W1KG5343
  ocr_software: Namsel
created_at: '2021-12-22T10:49:03.403669'
last_modified_at: '2021-12-22T10:49:03.403676'
statistics:
  total_words: 127740
  total_non_words: 18015
quality:
  non_words_ratio: 0.14
